[SKRB-146] feat: user 도메인 생성 및 검증 로직 테스트
Space-Club/Backend pull request #10
Opened 2023-10-24 16:22 UTC by juno-junho

### 💠 Jira 티켓 링크
- [SKRB-146](https://mapda.atlassian.net/jira/software/projects/SKRB/boards/1?selectedIssue=SKRB-146)
  <br>

### 🖥️ 작업 내용
- 유저는 다음과 같은 기능을 가집니다.
    - 필수 정보
        -  닉네임 (공백 포함 불가, null 불가, 2글자 이상 10자 이하)
        - 휴대폰 번호 ( 01x-(3~4글자)-(4글자) 형식 검증, - 여부는 자유) -> 저장시 - 제거
    - oauth 유저이름
    -  oauth 제공사 (확장 생각해서 분리했습니다)
    - 이메일 (x@x.(2~6글자 도메인) 으로 검증, 대소문자 구분 x) -> 추후 좀 더 고민 할 예정
    - refresh Token
<br>

### ✅ PR시 확인 사항
- [x] 테스트 코드 작성
- [x] Linear History 여부
  <br>

### 📢 리뷰어 전달 사항
- 테스트 컨벤션 관해서 좀더 이야기 해봅시다!

2023-10-24 16:38 UTC, hyeon-z requested changes
커밋이 9개로 PR단위가 크다는 생각이 듭니다..!

2023-10-24 16:38 UTC, hyeon-z commented on src/main/java/com/spaceclub/user/domain/Provider.java
> +}
위아래 엔터 넣어주세요! (컨벤션)

2023-10-24 16:38 UTC, hyeon-z commented on src/main/java/com/spaceclub/user/domain/RequiredInfo.java
> +
엔터 지워주세요!

2023-10-24 16:38 UTC, hyeon-z commented on src/main/java/com/spaceclub/user/domain/RequiredInfo.java
> +        Assert.isTrue(!nickname.contains(" "), "닉네임에 공백을 포함할 수 없습니다.");
닉네임에서 공백을 막는 이유가 있을까요?

2023-10-24 16:38 UTC, hyeon-z commented on src/main/java/com/spaceclub/user/domain/RequiredInfo.java
> +    private boolean isInValidRange(String nickname) {
`isInvalidRange`가 자연스러운 것 같습니다.

2023-10-24 16:38 UTC, hyeon-z commented on src/main/java/com/spaceclub/user/domain/User.java
> +    private RequiredInfo requiredInfo;
`RequiredInfo`라는 뜻이 애매한 것 같습니다. `UserInfo`는 어떨까요?

2023-10-24 16:38 UTC, hyeon-z commented on src/main/java/com/spaceclub/user/domain/User.java
> +    private String oauthUserName;
해당 값은 어떤 값인가요?

2023-10-24 17:13 UTC, hyeon-z requested changes

2023-10-24 17:13 UTC, hyeon-z commented on src/test/java/com/spaceclub/user/domain/EmailTest.java
> +    void 이메일의_형식이_올바르면_예외를_발생하지_않는다() {
**예외를 발생하지 않는다**를 **성공한다**로 바꿔주세요!

2023-10-25 04:25 UTC, juno-junho commented on src/main/java/com/spaceclub/user/domain/RequiredInfo.java
> +        Assert.isTrue(!nickname.contains(" "), "닉네임에 공백을 포함할 수 없습니다.");
공백 막는건 정책이니 공백 막지 말까요? 안막는게 좋을까요

2023-10-25 04:25 UTC, juno-junho commented on src/main/java/com/spaceclub/user/domain/RequiredInfo.java
> +    private boolean isInValidRange(String nickname) {
invalid가 아니라 유효한 범위 안인지 확인하는 is in valid range 입니다 :)

2023-10-25 04:25 UTC, juno-junho commented on src/main/java/com/spaceclub/user/domain/User.java
> +    private RequiredInfo requiredInfo;
UserInfo는 email도 user info인데, 필수적으로 입력받아야 하는 값 (닉네임, 전화번호) 만 설정한거에요

2023-10-25 04:25 UTC, juno-junho commented on src/main/java/com/spaceclub/user/domain/User.java
> +    private String oauthUserName;
카카오 서버로 부터 받는 사용자 식별 값입니다

2023-10-25 04:30 UTC, hyeon-z commented on src/main/java/com/spaceclub/user/domain/RequiredInfo.java
> +        Assert.isTrue(!nickname.contains(" "), "닉네임에 공백을 포함할 수 없습니다.");
전체 공백인 경우 (ex. "          ")는 막아야하지만 닉네임의 경우 중간 공백은 자연스럽다는 생각이 들었습니다! (ex. "바다의 왕자)

2023-10-25 04:31 UTC, hyeon-z commented on src/main/java/com/spaceclub/user/domain/RequiredInfo.java
> +    private boolean isInValidRange(String nickname) {
valid의 반대말인 invalid와 혼동의 여지가 있을 것 같은데 `checkValidRange`같은 메서드 명은 어떠신가요?

2023-10-25 04:32 UTC, hyeon-z commented on src/main/java/com/spaceclub/user/domain/User.java
> +    private String oauthUserName;
잘 감이 오지 않는데 식별 값의 예시가 있나요?

2023-10-25 04:34 UTC, choi5798 commented on src/main/java/com/spaceclub/user/domain/RequiredInfo.java
> +    private boolean isInValidRange(String nickname) {
그냥 유효한지 검사하기 위한 메소드라면 isValid 는 어떠신가요?

2023-10-25 04:35 UTC, hyeon-z commented on src/main/java/com/spaceclub/user/domain/User.java
> +    private RequiredInfo requiredInfo;
나머지도 결국 다 필수적으로 입력되는 값인데 **사용자에게 입력받는 값**을 나타내는 이름(ex. input이 들어간)이면 좋을 것 같다는 생각이 듭니다..! (참고 의견입니다.)

2023-10-25 04:37 UTC, juno-junho commented on src/main/java/com/spaceclub/user/domain/RequiredInfo.java
> +        Assert.isTrue(!nickname.contains(" "), "닉네임에 공백을 포함할 수 없습니다.");
아 굳... 수정할게요
입력 받은 값 trim 해서 10글자 제한으로 설정할게요

2023-10-25 04:38 UTC, juno-junho commented on src/main/java/com/spaceclub/user/domain/RequiredInfo.java
> +        Assert.isTrue(!nickname.contains(" "), "닉네임에 공백을 포함할 수 없습니다.");
(중간 enter 설정 가능)

2023-10-25 04:39 UTC, juno-junho commented on src/main/java/com/spaceclub/user/domain/RequiredInfo.java
> +    private boolean isInValidRange(String nickname) {
is valid range => isValidRange로 수정할게요

2023-10-25 04:41 UTC, choi5798 reviewed
수고하셨습니다~ 코멘트 몇 개 남겼어요

2023-10-25 04:41 UTC, choi5798 commented on src/main/java/com/spaceclub/user/domain/RequiredInfo.java
> +    public static final int MAX_NICKNAME_LENGTH = 10;
닉네임의 최소/최대 길이를 나타내는 변수를 public 으로 열어둔 이유가 있나요?

2023-10-25 04:41 UTC, choi5798 commented on src/main/java/com/spaceclub/user/domain/RequiredInfo.java
> +        Assert.isTrue(!nickname.contains(" "), "닉네임에 공백을 포함할 수 없습니다.");
중간 공백은 필요하다고 생각합니다

2023-10-25 04:43 UTC, juno-junho commented on src/main/java/com/spaceclub/user/domain/RequiredInfo.java
> +    public static final int MAX_NICKNAME_LENGTH = 10;
아하 변경할게요

2023-10-25 04:48 UTC, juno-junho commented on src/main/java/com/spaceclub/user/domain/User.java
> +    private String oauthUserName;
커스텀하게 만들어 줘야하는값인데, 카카오에서 넘어오는 id값이랑 + provider를 조합해서 만들면 될것 같아요
e.g) kakao_12345678

2023-10-25 04:50 UTC, hyeon-z commented on src/main/java/com/spaceclub/user/domain/User.java
> +    private String oauthUserName;
해당 값을 저장해야하는 이유가 있을까요?
쓰이는 곳이 있는 지 궁금합니다.

2023-10-25 09:37 UTC, hyeon-z approved these changes
🫡

2023-10-25 13:24 UTC, hyeon-z approved these changes
👍

2023-10-25 13:52 UTC, choi5798 approved these changes
LGTM

2023-10-25 16:10 UTC, merged