[SKRB-256] refactor: 초대 링크 도메인 분리, docs 반영
Space-Club/Backend pull request #100
Opened 2023-11-08 14:22 UTC by choi5798

### 💠 Jira 티켓 링크
- [SKRB-256](https://space-club.atlassian.net/jira/software/projects/SKRB/boards/1?selectedIssue=SKRB-256)
  <br>

### 🖥️ 작업 내용
- 초대 링크 도메인 분리
- 초대 링크 관련 api 검증 헤더 적용
- api 검증 헤더 요구 docs에 반영
<br>

### ✅ PR시 확인 사항
- [ ] Linear History 여부
- [ ] Postman QA 여부
  <br>

### 📢 리뷰어 전달 사항
- file changed는 많지만 전체적인 흐름에서 크게 달라진 것은 없습니다 (refactor: 를 붙인 이유)
- 초대 링크 도메인이 분리됐기 때문에 저희 RDS의 스키마를 한 번 업데이트 해줘야 합니다

2023-11-08 15:20 UTC, juno-junho approved these changes
성원님 고생 많으셨어요..! 👍

2023-11-09 11:04 UTC, hyeon-z requested changes
👍 리펙토링 굿! 리뷰 하나 확인해주세요~!

2023-11-09 11:04 UTC, hyeon-z commented on src/main/resources/local/application-local.yml
> +      ddl-auto: update
설정은 none으로 유지하고 테이블 구조를 rds상에서 업데이트 하면 좋을 것 같은데 어떠실까요?

2023-11-09 16:39 UTC, choi5798 commented on src/main/resources/local/application-local.yml
> +      ddl-auto: update
이거 local 프로파일이라 실제 저희 RDS에 반영 안되는 설정이에요
로컬에서 ddl 다시 생성하면서 기존 데이터 날리는 문제 없애려고 이렇게 바꿨어요

2023-11-09 22:54 UTC, hyeon-z approved these changes
👍

2023-11-10 01:09 UTC, merged