[SKRB-288] feat: 행사 폼 양식 생성하기 API 구현
Space-Club/Backend pull request #104
Opened 2023-11-10 14:22 UTC by hyeon-z

### 💠 Jira 티켓 링크
- [SKRB-288](https://space-club.atlassian.net/browse/SKRB-288)
  <br>

### 🖥️ 작업 내용
- 폼 관련 테이블 명 변경 및 컬럼 추가
- 행사 폼 양식 생성하기 API 구현
<br>

### ✅ PR시 확인 사항
- [ ] Linear History 여부
  <br>

### 📢 리뷰어 전달 사항

FormItem에서 Item을 Option으로 수정해서 file changed가 늘어났습니다🥲

2023-11-10 14:47 UTC, choi5798 requested changes
수고하셨습니다!
현지님 화이팅~ 해야줴~~

2023-11-10 14:47 UTC, choi5798 commented on src/main/java/com/spaceclub/form/domain/FormOption.java
> +    private Long id;
컬럼 이름도 바꿔주세요!

2023-11-10 14:47 UTC, choi5798 commented on src/main/java/com/spaceclub/form/controller/FormController.java
> +        );
dto를 vo로 통째로 옮긴 다음 vo 안에서 dto의 내용물들을 꺼내담는 방식은 어떠신가요?

2023-11-10 15:04 UTC, hyeon-z commented on src/main/java/com/spaceclub/form/domain/FormOption.java
> +    private Long id;
예리 선배..🫡

2023-11-10 15:08 UTC, hyeon-z commented on src/main/java/com/spaceclub/form/controller/FormController.java
> +        );
두 리뷰 다 반영 완료했습니다!
[chore: 리뷰 반영](https://github.com/Space-Club/Backend/pull/104/commits/db8c4b68c58868dcc953c6c2fa0b6f0872c7a3e8)

2023-11-10 15:10 UTC, choi5798 approved these changes
💯

2023-11-11 02:56 UTC, juno-junho approved these changes
👍

2023-11-11 03:05 UTC, merged