[SKRB-296] feat: 유저의 행사 북마크 상태 변경 기능 구현
Space-Club/Backend pull request #121
Opened 2023-11-12 16:45 UTC by juno-junho

### 💠 Jira 티켓 링크
- [SKRB-296](https://space-club.atlassian.net/jira/software/projects/SKRB/boards/1/backlog?selectedIssue=SKRB-296)
  <br>

### 🖥️ 작업 내용
- 북마크 상태 변경 기능 구현
<br>

### ✅ PR시 확인 사항
- [ ] Linear History 여부
  <br>

### 📢 리뷰어 전달 사항

2023-11-12 17:10 UTC, choi5798 reviewed
고생하셨어요~ 궁금한점 몇개 남겼어요

2023-11-12 17:10 UTC, choi5798 commented on src/main/java/com/spaceclub/event/domain/EventUser.java
> +    public EventUser bookmark(boolean bookmarkStatus) {
bookmark 메소드 하나로 bookmark 설정과 취소 다 처리하는 건가요

2023-11-12 17:10 UTC, choi5798 commented on src/main/java/com/spaceclub/user/controller/dto/UserBookmarkedEventGetResponse.java
> +        public static UserBookmarkedEventGetResponse of(Event event, boolean bookmarkStatus) {
북마크 상태를 나타내는 파라미터를 다시 받게 바뀌었는데 함수 안에서는 안 쓰이고 있어요

2023-11-12 17:23 UTC, juno-junho commented on src/main/java/com/spaceclub/event/domain/EventUser.java
> +    public EventUser bookmark(boolean bookmarkStatus) {
네네 맞아요 그냥 상태변경만 하는거에요

2023-11-12 17:30 UTC, hyeon-z requested changes
EventUser는 유저가 이벤트를 신청한 것을 관리하는 테이블이라서 따로 연관관계 테이블을 만들어야할 것 같습니다!

2023-11-13 00:03 UTC, juno-junho commented on src/main/java/com/spaceclub/user/controller/dto/UserBookmarkedEventGetResponse.java
> +        public static UserBookmarkedEventGetResponse of(Event event, boolean bookmarkStatus) {
rebase 되면서 잘못 수정된것 같네요
수정했습니다!

2023-11-13 01:16 UTC, hyeon-z approved these changes
👍

2023-11-13 05:27 UTC, choi5798 approved these changes
👍

2023-11-13 05:30 UTC, merged