[SKRB-143] feat: 클럽 엔티티, 서비스 및 리포지토리 생성
Space-Club/Backend pull request #13
Opened 2023-10-25 05:01 UTC by choi5798

### 💠 Jira 티켓 링크
- [SKRB-143](https://mapda.atlassian.net/jira/software/projects/SKRB/boards/1?assignee=5c6a486415e48873c446b50a&selectedIssue=SKRB-143)
  <br>

### 🖥️ 작업 내용
- 클럽 엔티티를 만들고 그와 관련된 서비스, 리포지토리 구현 완료
<br>

### ✅ PR시 확인 사항
- [ ] 테스트 코드 작성
- [ ] Linear History 여부
  <br>

### 📢 리뷰어 전달 사항
- 테스트 코드는 아직 별다른 기능이 없어 작성하지 않았습니다.

2023-10-25 05:03 UTC, hyeon-z approved these changes
🫡

2023-10-25 05:03 UTC, hyeon-z commented on src/main/java/com/spaceclub/club/domain/Club.java
> +        Assert.hasText(Long.toString(id), "클럽 ID는 빈 값이 올 수 없습니다");
id는 Long형인데 String으로 바꿔서 빈 값인지 테스트하는 이유가 있을까요?

2023-10-25 05:06 UTC, choi5798 commented on src/main/java/com/spaceclub/club/domain/Club.java
> +        Assert.hasText(Long.toString(id), "클럽 ID는 빈 값이 올 수 없습니다");
Assert.hasText 메소드의 첫번째 파라미터 타입이 String 으로 받게끔 되어있더라고요

2023-10-25 08:28 UTC, hyeon-z commented on src/main/java/com/spaceclub/club/domain/Club.java
> +        Assert.hasText(Long.toString(id), "클럽 ID는 빈 값이 올 수 없습니다");
Long형에 숫자 타입인데 빈 값을 검사해야 되는 지가 궁금했습니다!

2023-10-25 08:33 UTC, juno-junho requested changes
고생하셨습니다! 화이팅 !! 🥂

2023-10-25 08:33 UTC, juno-junho commented on src/main/java/com/spaceclub/club/controller/ClubController.java
>      @PostMapping("/club")
REST API 컨벤션에 따라서 clubs라 변경일 필요해 보여요!

2023-10-25 08:33 UTC, juno-junho commented on src/main/java/com/spaceclub/club/domain/Club.java
> +    @Column(length = 12, nullable = false)
클럽 이름 길이를 12자로 제한하는 것으로 설정하신건가요?
그러면 DB 단에서도 제약조건을 걸어 주었듯 어플리케이션 단에서 생성자에서 객체 생성 자체를 막는 과정도 필요해 보여요

2023-10-25 08:33 UTC, juno-junho commented on src/main/java/com/spaceclub/club/domain/Club.java
> +        Assert.hasText(Long.toString(id), "클럽 ID는 빈 값이 올 수 없습니다");
hasText에 notnull이 포함되어 있기 때문에 not null은 제거해줘도 될것같아요~

2023-10-25 08:35 UTC, juno-junho commented on src/main/java/com/spaceclub/club/domain/Club.java
> +        Assert.hasText(Long.toString(id), "클럽 ID는 빈 값이 올 수 없습니다");
id뿐 아니라 name, image또한 강제한다면 hasText로 검증이 필요해보여요

2023-10-25 09:02 UTC, choi5798 commented on src/main/java/com/spaceclub/club/controller/ClubController.java
>      @PostMapping("/club")
단건에 대한 처리인데도 전부 다 복수명사를 사용해야하나요?

2023-10-25 09:06 UTC, choi5798 commented on src/main/java/com/spaceclub/club/domain/Club.java
> +        Assert.hasText(Long.toString(id), "클럽 ID는 빈 값이 올 수 없습니다");
id는 자동 생성이기 때문에 해당 검증문은 제거 했습니다

2023-10-25 09:23 UTC, choi5798 commented on src/main/java/com/spaceclub/club/domain/Club.java
> +        Assert.hasText(Long.toString(id), "클럽 ID는 빈 값이 올 수 없습니다");
id는 자동생성될 필드라서 검증은 삭제했고 name 검증은 추가 했습니다

2023-10-25 10:22 UTC, juno-junho commented on src/main/java/com/spaceclub/club/controller/ClubController.java
>      @PostMapping("/club")
네 기본이 복수를 원칙으로 하는것으로 알고있어요
특정 자원에 접근하는것이 아니라 어떤 자원에 접근하는지를 뜻하니까요
그리고 하나의 클럽에 접근하는 것이면  clubs/{clubId}로 접근하는것이 좋아보여요

2023-10-25 10:22 UTC, juno-junho commented on src/main/java/com/spaceclub/club/controller/ClubController.java
>      @PostMapping("/club")
그리괘 club을 생성하고난 후 왜 도메인 실제 url을 보여주나요?
location을 통해서 생성된 club에 접근할 수 있는 uri를 보여주는게 낫다고 생각해요

2023-10-25 10:22 UTC, juno-junho commented
고생하셨는데 RESTful 하지 못한 부분만 변경 부탁드리겠습니다 !! 👍

2023-10-25 12:17 UTC, choi5798 commented on src/main/java/com/spaceclub/club/controller/ClubController.java
>      @PostMapping("/club")
club에 접근할 수 있는 uri 는 어떤 형태로 생긴건가요?

2023-10-25 13:49 UTC, choi5798 commented on src/main/java/com/spaceclub/club/controller/ClubController.java
>      @PostMapping("/club")
[fix: api endpoint 수정, location 값 수정](https://github.com/Space-Club/Backend/pull/13/commits/33d0af0620f5b99181040d873bd8d23416c03807)
반영했습니다

2023-10-25 13:49 UTC, choi5798 commented on src/main/java/com/spaceclub/club/domain/Club.java
> +    @Column(length = 12, nullable = false)
[feat: Club 엔티티 owner 필드 추가, 이름 길이 검증 추가](https://github.com/Space-Club/Backend/pull/13/commits/98e356e04da43b272915f2ee374a5ec3fee47644)
반영했습니다

2023-10-26 01:55 UTC, juno-junho approved these changes
👍

2023-10-26 04:07 UTC, merged