[SKRB-156] feat: 클럽 조회, 그와 관련된 보조 테이블 생성과 연관관계 설정
Space-Club/Backend pull request #16
Opened 2023-10-26 08:39 UTC by choi5798

### 💠 Jira 티켓 링크
- [SKRB-156](https://mapda.atlassian.net/jira/software/projects/SKRB/boards/1?selectedIssue=SKRB-156)
  <br>

### 🖥️ 작업 내용
- 클럽을 조회하는 과정에서 필요한 내용들에 대한 새로운 Entity 및 연관관계 설정
- Club Entity와 User Entity간의 연관관계 설정
<br>

### ✅ PR시 확인 사항
- [ ] 테스트 코드 작성
- [ ] Linear History 여부
  <br>

### 📢 리뷰어 전달 사항

2023-10-26 08:50 UTC, hyeon-z approved these changes
👍

2023-10-26 09:24 UTC, juno-junho requested changes
성원님 고생하셨습니다!
제가 느끼기에 수정이 필요한 지점에 커멘트 달았는데 한번 확인 부탁드립니다 🤙

2023-10-26 09:24 UTC, juno-junho commented on src/main/java/com/spaceclub/club/controller/dto/ClubGetResponse.java
> +        String[] notices
왜 List대신에 배열을 사용하셨나요?

2023-10-26 09:24 UTC, juno-junho commented on src/main/java/com/spaceclub/club/domain/ClubUser.java
> +    @Column(length = 16, nullable = false)
이런 정책을 만들었으면 문서화 시켜서 공유해야 할것 같은데 유저스토리나 티켓에 팀원들하고 이야기해서 같이 남기는게 필요할것같네용

2023-10-26 09:24 UTC, juno-junho commented on src/main/java/com/spaceclub/club/service/ClubService.java
위 create할때 트렌젝션 처리가 안되어있어요

2023-10-26 09:24 UTC, juno-junho commented on src/main/java/com/spaceclub/club/domain/Club.java
> +        if (notices != null) {
이건 왜 추가해주셨나요?

2023-10-26 09:24 UTC, juno-junho commented on src/main/java/com/spaceclub/club/domain/Club.java
> +    public ClubGetResponse toGetResponseDto() {
DTO를 엔티티에서 생성하는게 도메인 객체 책임과 멀어진것 같아요
DTO는 컨트롤러와 view 사이에서 데이터를 주고 받는 객체인데 도메인이 아닌 컨트롤러에서 생성해야 할것 같아요

2023-10-26 09:24 UTC, juno-junho commented on src/main/java/com/spaceclub/club/domain/ClubNotice.java
> +    private String notice;
공지사항이면 꽤 길이 길어지는 mysql TEXT 형식일건데,
`@Lob` 사용하는게 어떨까요?

2023-10-26 09:24 UTC, juno-junho commented on src/test/java/com/spaceclub/club/controller/ClubControllerTest.java
>      @WithMockUser
Displayname 테스트 관련 컨벤션 확인부탁합니다!

2023-10-26 09:24 UTC, juno-junho commented on src/test/java/com/spaceclub/club/controller/ClubControllerTest.java
> +                        )));
괄호 위같이 일관되게 작성해주세요

2023-10-26 13:25 UTC, choi5798 commented on src/main/java/com/spaceclub/club/controller/dto/ClubGetResponse.java
> +        String[] notices
List<ClubNotice>로 반환을 하니 responseBody에 notices: [ {} ] 이렇게 뜨더라고요
그래서 타입을 바꿔주기 위해 배열을 사용했습니다

2023-10-26 13:26 UTC, choi5798 commented on src/main/java/com/spaceclub/club/domain/ClubUser.java
> +    @Column(length = 16, nullable = false)
이 role에 대한 길이 제한은 제가 임의로 한 것이 아니고 저희 노션에 작성된 ERD보고 만들었습니다
확인해보시겠어요?

2023-10-26 13:28 UTC, choi5798 commented on src/main/java/com/spaceclub/club/domain/ClubNotice.java
> +    private String notice;
하나의 텍스트로 공지사항을 적는 게 아니라 여러 항목으로 나눠서 저장할 수 있게끔 일대다 매핑이 되어있습니다
그래서 공지사항이 List로 각각 저장되어 있기 때문에 단순 VARCHAR(255)로도 충분히 커버될 것 같아요

2023-10-26 13:29 UTC, choi5798 commented on src/main/java/com/spaceclub/club/domain/Club.java
> +        if (notices != null) {
notices가 null일 경우 new ArrayList<>(notices)의 인자로 들어갈 때 NPE가 발생해서 추가했어요

2023-10-26 13:31 UTC, choi5798 commented on src/test/java/com/spaceclub/club/controller/ClubControllerTest.java
> +                        )));
위같이 라는게 어떤 의미인가요?

2023-10-27 02:24 UTC, choi5798 commented on src/main/java/com/spaceclub/club/domain/Club.java
> +    public ClubGetResponse toGetResponseDto() {
컨트롤러에서 dto를 생성하려면 엔티티객체에서 getter로 필요한 필드를 다 가져와야해서 getter 없이 구현하기 위해 도메인에서 구현했어요

2023-10-27 04:47 UTC, juno-junho commented on src/main/java/com/spaceclub/club/domain/ClubUser.java
> +    @Column(length = 16, nullable = false)
erd는 varchar로 그냥 임의로 정한거라 확정값은 아니에요

2023-10-27 05:33 UTC, juno-junho approved these changes
👍

2023-10-27 05:33 UTC, juno-junho commented on src/test/java/com/spaceclub/club/controller/ClubControllerTest.java
> +                        )));
<img width="896" alt="image" src="https://github.com/Space-Club/Backend/assets/72647031/e0dc9a41-8fed-4f2c-a4d6-8c456f4e70b6">

2023-10-27 05:33 UTC, juno-junho commented on src/test/java/com/spaceclub/club/controller/ClubControllerTest.java
> +                        )));
괄호를 띄우거나 붙히거나 하나의 형식으로 통일 되게 작성하면 좋을것 같아요
+ 시큐리티 기능 꺼놔서 `with(csrf())` 설정하지 않아도 테스트 통과할거에요

2023-10-27 05:33 UTC, juno-junho commented on src/main/java/com/spaceclub/club/domain/Club.java
> +    public ClubGetResponse toGetResponseDto() {
그러면 dto 스펙이 바뀌면 domain과 dto를 둘다 수정해줘야 하기 때문에
응집도가 떨어지게 되는것 같아 저는 개인적으로는 좋아보이진 않아서요
일단 기능 구현이 우선이니 머지 하셔도 될것 같습니다!

2023-10-27 06:59 UTC, merged