[SRKB-170] feat: 로그인 및 회원가입 시 refresh token 발급 기능 구현
Space-Club/Backend pull request #163
Opened 2023-11-18 10:09 UTC by juno-junho

### 💠 Jira 티켓 링크
- [SRKB-170](https://space-club.atlassian.net/jira/software/projects/SKRB/boards/1?selectedIssue=SKRB-170)
  <br>

### 🖥️ 작업 내용
- 회원 가입 및 로그인 시 refresh token 발급 기능 구현
- 발급 시에는 user 테이블의 db 컬럼을 update합니다.
<br>

### ✅ PR시 확인 사항
- [x] Linear History 여부
- [x] Postman QA 여부 
<img width="1223" alt="image" src="https://github.com/Space-Club/Backend/assets/72647031/84e1c9ee-5a0d-4471-9ece-55119e161a1c">

  <br>

### 📢 리뷰어 전달 사항

2023-11-18 11:07 UTC, hyeon-z requested changes
해당 컨벤션만 반영해주세요!

2023-11-18 11:07 UTC, hyeon-z commented on src/main/java/com/spaceclub/user/domain/User.java
> +    }
setter 사용 x 컨벤션입니다!

2023-11-18 11:43 UTC, juno-junho commented on src/main/java/com/spaceclub/user/domain/User.java
> +    }
이때까지 setter를 사용해서 사용해도 되는줄 알았어요
이게 user builder 생성자에서 파라미터로 받은 값을 저장하기 전에 처리해 주는 작업이 있어서
기존 builder는 처음 객체 생성시에만 사용가능하고 나머지는 사용이 불가할 것 같아요

그러면 생성자를 하나 더 만들어 불변으로 유지하는게 맞을까요?

2023-11-18 11:44 UTC, juno-junho commented on src/main/java/com/spaceclub/user/domain/User.java
> +    }
@hyeon-z

2023-11-18 16:14 UTC, choi5798 approved these changes
👍

2023-11-18 16:14 UTC, choi5798 commented on src/main/java/com/spaceclub/user/domain/User.java
> +    }
네 그러면 해당 상황에 맞는 생성자를 하나 더 만드시죠!

2023-11-18 19:28 UTC, hyeon-z commented on src/main/java/com/spaceclub/user/domain/User.java
> +    }
넵 그런 상황이라면 하나 더 만들어야할 것 같네요!

2023-11-19 07:56 UTC, juno-junho commented on src/main/java/com/spaceclub/user/domain/User.java
> +    }
수정 완료 :)

2023-11-19 08:00 UTC, hyeon-z approved these changes
👍

2023-11-19 08:01 UTC, merged