[SKRB-337] feat: 클럽 조회시 클럽 유저 권한 조회 api 분리
Space-Club/Backend pull request #165
Opened 2023-11-18 12:15 UTC by juno-junho

### 💠 Jira 티켓 링크
- [SKRB-337](https://space-club.atlassian.net/jira/software/projects/SKRB/boards/1?selectedIssue=SKRB-337)
  <br>

### 🖥️ 작업 내용
== 제목

<br>

### ✅ PR시 확인 사항
- [x] Linear History 여부
- [ ] Postman QA 여부 (분리만 한거라 테스트는 안했어요. 머지 되면 바로 혜성님한테 피드백 받을 생각입니다.)
  <br>

### 📢 리뷰어 전달 사항
마지막 한 커밋만 보면 됩니다.

2023-11-18 16:33 UTC, choi5798 requested changes
👍 
몇가지 코멘트 남겼어요~

2023-11-18 16:33 UTC, choi5798 commented on src/main/java/com/spaceclub/club/controller/ClubController.java
> +    @GetMapping("/clubs/{clubId}/users")
API 엔드포인트를 통해 해당 클럽의 유저 정보를 가져오겠다는건 알겠는데 유저의 role을 가져오겠다는 의미는 잘 안느껴져요
유저의 role을 가져오는 api임을 좀 더 잘 보여줄 수 있는 엔드포인트로 설정하는 것은 어떨까요?
예시)
``` suggestion
    @GetMapping("/clubs/{clubId}/users-role")
```

2023-11-18 16:33 UTC, choi5798 commented on src/test/java/com/spaceclub/club/controller/ClubControllerTest.java
> +                                        headerWithName(AUTHORIZATION).description("Access Token")
액세스 토큰의 설명 부분은 다른 api들에 적혀 있는 설명과 통일시켜 주세요

2023-11-18 19:43 UTC, hyeon-z approved these changes
👍

2023-11-19 08:00 UTC, juno-junho commented on src/main/java/com/spaceclub/club/controller/ClubController.java
> +    @GetMapping("/clubs/{clubId}/users")
제가 알기로는 endpoint 설정 시 어떤 자원을 가지고 오는지에 대해서 상세하게 기술하지 않는것으로 알고 있어요
그래서 role이라고 명확하게 하지 않은거고요
clubId의 User에 대한 정보를 가지고 오는거라 (추후 role 말고도 수정될 수가 있으니) role이라 명시하지 않은거에요

2023-11-19 08:25 UTC, choi5798 approved these changes
네 알겠습니다
test failed 만 고쳐서 머지 해주세요~

2023-11-19 08:33 UTC, merged