[SKRB-386] fix: 행사 수정 club이 null이 되는 오류 수정 및 posterImage 선택 값 처리
Space-Club/Backend pull request #200
Opened 2023-11-22 09:33 UTC by hyeon-z

### 💠 Jira 티켓 링크
- [SKRB-386](https://space-club.atlassian.net/browse/SKRB-386)
  <br>

### 🖥️ 작업 내용
- 행사 수정 club이 null이 되는 오류 수정 및 posterImage 선택 값 처리
- Club 이미지 관련 null일 때 url 처리
<br>

### ✅ PR시 확인 사항
- [ ] Linear History 여부
- [ ] Postman QA 여부
  <br>

### 📢 리뷰어 전달 사항

2023-11-22 09:35 UTC, juno-junho approved these changes
👍

2023-11-22 09:47 UTC, choi5798 requested changes
수고수고!

2023-11-22 09:47 UTC, choi5798 commented on src/main/java/com/spaceclub/event/domain/Event.java
> +    }
여기 마지막에 build() 가 빠져서 return 타입이 바뀌었는데 Builder 객체를 반환하려고 의도하신건가요?

2023-11-22 09:47 UTC, choi5798 commented on src/main/java/com/spaceclub/event/domain/EventInfo.java
> +        this.posterImageName = posterImageUrl;
오른쪽에 있는 변수명도 똑같이 맞춰주세요

2023-11-22 09:47 UTC, choi5798 commented on src/main/java/com/spaceclub/event/service/EventService.java
> +        Event existEvent = eventValidator.validateEvent(event.getId());
validator 가 어떤건 객체를 반환하고 어떤건 검증만 하고 있는데 return 없이 검증만 하게끔 역할이 통일되어야 할 것 같아요

2023-11-22 09:47 UTC, choi5798 commented on src/main/java/com/spaceclub/event/service/EventService.java
> +        return events.stream().map(SchedulesGetInfo::from).toList();
저희 같은 줄에 점 2개 이상 찍지 않기로 하지 않았었나요?

2023-11-22 09:47 UTC, choi5798 commented on src/test/java/com/spaceclub/event/domain/EventInfoTest.java
> +                        .posterImageUrl(eventInfo().getPosterImageName())
포스터 이미지 URL 에 포스터 이미지 이름을 넣어주고 있는데 둘이 같은 형식인가요?

2023-11-23 06:40 UTC, hyeon-z commented on src/main/java/com/spaceclub/event/domain/Event.java
> +    }
넵 맞습니다! 특정 컬럼 값만 바꿀 때 해당 컬럼만 넣어줘서 쓸 수 있어서 해당 방식으로 바꾸었습니다!

2023-11-23 06:57 UTC, hyeon-z commented on src/main/java/com/spaceclub/event/service/EventService.java
> +        return events.stream().map(SchedulesGetInfo::from).toList();
아 단축키를 썼더니 자동 정렬된 것 같네요! 다시 돌려놓겠습니다!

2023-11-23 07:10 UTC, hyeon-z commented
@choi5798 확인 한 번 부탁드릴게요~ 
[chore: 리뷰 반영](https://github.com/Space-Club/Backend/pull/200/commits/01ebe0f57538fb9cd0703aa341101f990b6bcadf)

2023-11-23 07:16 UTC, choi5798 approved these changes
굿굿

2023-11-23 07:16 UTC, choi5798 commented on src/main/java/com/spaceclub/event/service/EventService.java
> +        clubUserValidator.validateClubManager(createInfo.clubId(), createInfo.userId());
👍

2023-11-23 07:28 UTC, merged