[SKRB-110] feat: user 도메인 생성자 변경 및 기본 값 설정
Space-Club/Backend pull request #68
Opened 2023-11-02 11:13 UTC by juno-junho

### 💠 Jira 티켓 링크
- [SKRB-110](https://space-club.atlassian.net/jira/software/projects/SKRB/boards/1?selectedIssue=SKRB-110)
  <br>

### 🖥️ 작업 내용
- 유저 도메인 변경
<br>

### ✅ PR시 확인 사항
- [ ] Linear History 여부
  <br>

### 📢 리뷰어 전달 사항
- 폭풍 pr 준비중..

2023-11-02 14:15 UTC, hyeon-z requested changes
궁금한 점 몇 개 남겼습니다!

2023-11-02 14:15 UTC, hyeon-z commented on src/main/java/com/spaceclub/user/domain/PhoneNumber.java
> +    @Column(nullable = false, columnDefinition = "varchar(11) default UNKNOWN")
default값을 `UNKNOWN`으로 지정한 이유가 있나요? (아래 `nickname`도 같은 질문)

2023-11-02 14:15 UTC, hyeon-z commented on src/main/java/com/spaceclub/user/domain/User.java
> +    private String password;
`password`가 어떤 값인가요?

2023-11-02 14:15 UTC, hyeon-z commented on src/main/java/com/spaceclub/user/domain/User.java
> +    }
해당 값을 저장하는 이유가 있나요? 어떨 때 사용되나요?

2023-11-02 14:15 UTC, hyeon-z commented on src/main/java/com/spaceclub/global/oauth/service/vo/KakaoUserInfo.java
> +    }
라인 맞춰주세요!

2023-11-02 14:15 UTC, hyeon-z commented on src/main/java/com/spaceclub/global/oauth/service/vo/KakaoTokenInfo.java
> +@JsonNaming(value = SnakeCaseStrategy.class)
해당 어노테이션을 붙여준 이유가 있나요?

2023-11-02 14:18 UTC, choi5798 approved these changes
굿 👍

2023-11-02 14:32 UTC, juno-junho commented on src/main/java/com/spaceclub/user/domain/User.java
> +    private String password;
엇 password 없애야 해요

2023-11-02 14:34 UTC, juno-junho commented on src/main/java/com/spaceclub/user/domain/PhoneNumber.java
> +    @Column(nullable = false, columnDefinition = "varchar(11) default UNKNOWN")
네 null로 설정하는건 npe의 위험도 있고  레이님이 예전에 값을 받을거면 다 받고 안받을거면 받지말라 하셨는데
값을 null로 받아버리면 null의 의미도 모호해질 뿐더러 진짜 있으면 안되는 값 null과 아직 입력하지 않은 정보를 구분하기 위해서 설정해야 한다고 생각해요

2023-11-02 14:35 UTC, juno-junho commented on src/main/java/com/spaceclub/global/oauth/service/vo/KakaoTokenInfo.java
> +@JsonNaming(value = SnakeCaseStrategy.class)
카카오 api는 response가 snake 표기에요
근데 자바는 기본이 카멜 표기잖아요? 그  간격을 맞추고, 자바 컨벤션을 깨고 싶지 않아서 해당 어노테이션을 사용했어요
![image](https://github.com/Space-Club/Backend/assets/72647031/64a7c146-3f82-4d2e-807b-68e5a7cc7c40)

2023-11-02 14:36 UTC, juno-junho commented on src/main/java/com/spaceclub/global/oauth/service/vo/KakaoTokenInfo.java
> +@JsonNaming(value = SnakeCaseStrategy.class)
+ 그래서 현지님도 data jpa의 기능을 자바 컨벤션을 깨뜨리면서 사용하는것도 저는 지양하는게 좋다고 생각하긴해요 (추후 리펙토링 항목이겠지만..)

2023-11-02 14:54 UTC, juno-junho commented on src/main/java/com/spaceclub/user/domain/User.java
> +    }
유저를 식별하는데 사용해요 카카오에서 주는 사용자 id값인데, 앞에 provider인 kakao를 붙인거에요

2023-11-02 15:59 UTC, hyeon-z commented on src/main/java/com/spaceclub/global/oauth/service/vo/KakaoTokenInfo.java
> +@JsonNaming(value = SnakeCaseStrategy.class)
추후 성원님과 함께 얘기해봐도 좋을 것 같아요!

2023-11-03 00:59 UTC, hyeon-z approved these changes
👍 수고하셨습니다!

2023-11-03 05:19 UTC, merged