[SKRB-148] 행사 생성 API 틀 구현
Space-Club/Backend pull request #8
Opened 2023-10-24 15:01 UTC by hyeon-z

### 💠 Jira 티켓 링크
- [KRB-148](https://mapda.atlassian.net/browse/SKRB-148)
  <br>

### 🖥️ 작업 내용
- 행사 생성 repository, service, controller 틀 구현
<br>

### ✅ PR시 확인 사항
- [ ] 테스트 코드 작성
- [ ] Linear History 여부
  <br>

### 📢 리뷰어 전달 사항

틀 구현을 위해 임시로 넣은 값
- controller의 location
- CreateEventRequest의 파라미터, toEntity 메서드
- Event 엔티티의 기본 생성자

2023-10-24 15:17 UTC, juno-junho approved these changes
커멘트 한번 확인해주세요 👍

2023-10-24 15:17 UTC, juno-junho commented on src/main/java/com/spaceclub/event/controller/dto/CreateEventRequest.java
> +public record CreateEventRequest(Long id) {
dto를 뽑아야 api 명세가 나오지 않나요?

2023-10-24 15:17 UTC, juno-junho commented on src/main/java/com/spaceclub/event/service/EventService.java
> +public class EventService {
서비스 인터페이스로 만들어 놓고 빠르게 api 명세 뽑아도 좋을것 같아요

2023-10-24 15:23 UTC, juno-junho commented
PR 제목 컨벤션 한번 확인해 주세요 feat이 빠졌어요

2023-10-24 16:28 UTC, hyeon-z commented on src/main/java/com/spaceclub/event/controller/dto/CreateEventRequest.java
> +public record CreateEventRequest(Long id) {
api틀 만든 PR 후 명세 관련 작업 커밋할 예정입니다! (DTO, controller 테스트)

2023-10-24 16:29 UTC, hyeon-z commented on src/main/java/com/spaceclub/event/service/EventService.java
> +public class EventService {
서비스를 mock으로 테스트할 예정이라 class로 만들었습니다!

2023-10-25 03:53 UTC, choi5798 requested changes
컨벤션 관련된 변경사항만 수정하면 될 것 같습니다~

2023-10-25 03:53 UTC, choi5798 commented on src/main/java/com/spaceclub/event/controller/EventController.java
> +    public ResponseEntity<Void> saveEvent(@RequestBody CreateEventRequest request) {
저희 컨트롤러, 서비스에서 생성 관련 메소드는 create로 시작하기로 컨벤션 정했어요

2023-10-25 03:53 UTC, choi5798 commented on src/main/java/com/spaceclub/event/domain/Event.java
> +//@NoArgsConstructor(access = AccessLevel.PROTECTED)
특별한 의미를 나타내지 않는 주석은 지워도 될 것 같아요

2023-10-25 04:43 UTC, hyeon-z commented on src/main/java/com/spaceclub/event/controller/EventController.java
> +    public ResponseEntity<Void> saveEvent(@RequestBody CreateEventRequest request) {
EventController내의 메서드명이라 Event를 때고 create로 변경했습니다.
[chore: controller 메서드 명 create으로 변경](https://github.com/Space-Club/Backend/pull/8/commits/7be4b17706facc07540bfd8db6021afb1db85823)

2023-10-25 04:43 UTC, hyeon-z commented on src/main/java/com/spaceclub/event/domain/Event.java
> +//@NoArgsConstructor(access = AccessLevel.PROTECTED)
API 틀을 만들기 위해 임시로 변경한 부분이라 주석처리 했습니다.

2023-10-25 04:57 UTC, choi5798 approved these changes
👍

2023-10-25 05:19 UTC, merged