[SKRB-252] feat: 유저 로그인 및 조회 추가 구현
Space-Club/Backend pull request #87
Opened 2023-11-06 20:02 UTC by hyeon-z

### 💠 Jira 티켓 링크
- [SKRB-252](https://space-club.atlassian.net/browse/SKRB-252)
  <br>

### 🖥️ 작업 내용
- 유저 로그인 관련 추가 구현
- Bearer 토큰 처리 구현
- 유저 이미지 조회, 프로필 조회 API에 토큰 처리 구현
- 유저 관련 API의 adoc명세 수정
<br>

### ✅ PR시 확인 사항
- [ ] Linear History 여부
  <br>

### 📢 리뷰어 전달 사항

로그인 및 유저 조회 관련해서 동작되지 않는 부분이 있어서 추가 구현 완료하였습니다.
토큰 만료 기간이 짧아서 임시로 늘려서 넣어두었습니다.

2023-11-06 20:38 UTC, juno-junho approved these changes
제가 맡은 부분 변경사항이 있네요
오늘 저녁부터는 게더 들어와볼게요 👍

2023-11-06 20:38 UTC, juno-junho commented on src/main/resources/local/application-oauth.yml
> +  expiry-seconds: 30000 # 임시 값
이거 일부러 5분으로 설정한건데 바꾸셨네요

2023-11-06 21:11 UTC, hyeon-z commented on src/main/resources/local/application-oauth.yml
> +  expiry-seconds: 30000 # 임시 값
테스트할 때 너무 짧아서 임시로 늘려놨어요🫡 리뷰어 전달사항 항목에 항목에 적어뒀습니다!

2023-11-07 02:49 UTC, choi5798 requested changes

2023-11-07 02:49 UTC, choi5798 commented on src/main/java/com/spaceclub/global/jwt/service/JwtService.java
> +        }
spring Assert 로 검증 진행해주세요 (컨벤션)

2023-11-07 02:49 UTC, choi5798 commented on src/main/java/com/spaceclub/user/repository/UserRepository.java
> +    @Query("select u from User u where u.email.email = :email and u.oauthUserName = :oauthUsername")
어째서.. email.email 같은 쿼리가 생기게 되었나요...

2023-11-07 02:51 UTC, hyeon-z commented on src/main/java/com/spaceclub/user/repository/UserRepository.java
> +    @Query("select u from User u where u.email.email = :email and u.oauthUserName = :oauthUsername")
그건은 Email 임베디드 클래스 안에 email이라는 컬럼을 접근해야하기 때문..

2023-11-07 02:55 UTC, hyeon-z commented on src/main/java/com/spaceclub/global/jwt/service/JwtService.java
> +        }
반영완료!
[chore: Assert 컨벤션 적용](https://github.com/Space-Club/Backend/pull/87/commits/e57273bafab7b18273288816cf775c5562cf7c86)

2023-11-07 02:56 UTC, choi5798 approved these changes
굳 👍

2023-11-07 03:00 UTC, hyeon-z commented on src/main/java/com/spaceclub/user/repository/UserRepository.java
> +    @Query("select u from User u where u.email.email = :email and u.oauthUserName = :oauthUsername")
개선 완료
[chore: JPQL 컬럼 명 중복 개선](https://github.com/Space-Club/Backend/pull/87/commits/612f2218be544dd9d670e5019d345f4bb9b6733a)

2023-11-07 03:05 UTC, merged